on: push
name: Rust
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.47.0  # MSRV

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        name: build
        with:
          args: --manifest-path rust/Cargo.toml
          command: build

      - uses: actions-rs/cargo@v1
        name: test
        with:
          args: --manifest-path rust/Cargo.toml
          command: test

      - uses: actions-rs/cargo@v1
        name: fmt
        with:
          command: fmt
          args: --manifest-path rust/Cargo.toml --all -- --check

      - uses: actions-rs/cargo@v1
        name: clippy
        with:
          command: clippy
          args: --manifest-path rust/Cargo.toml -- -D warnings

      - name: Check if there are changes
        run: |
          if [[ -z "$(git status --porcelain)" ]];
          then
            echo "No changes"
          else
            echo "Changes detected, you should use make go_proto and commit the changes"
            exit 1
          fi